#!/bin/zsh
source-with-force ${^ZDOTDIRS}/.profile(.-N)

case $OSTYPE in
    linux*)
        (( ! ${+commands[systemctl]} )) \
           ||  systemctl --user import-environment PATH
        ;;
esac

