#!/bin/zsh

zplug "zplug/zplug", lazy:true

# Finally
zplugins.load-all-in plugins

zplug "zsh-users/zsh-history-substring-search"
zplug "akatrevorjay/fasd"

zplug "willghatch/zsh-hooks"
#zplug "mafredri/zsh-async"
zplug "kennethreitz/autoenv"

zplug "akatrevorjay/composure", lazy:true
zplug "psprint/zsnapshot", lazy:true
zplug "mollifier/zload", lazy:true
zplug "Tarrasch/zsh-functional", lazy:true
#zplug "Tarrasch/zsh-bd", lazy:true
#zplug "Tarrasch/zsh-colors", lazy:true
#zplug "b4b4r07/emoji-cli", lazy:true
#zplug 'LockonS/terminal-workload-report', lazy:true
#zplug 'aphelionz/strerror.plugin.zsh', lazy:true
zplug "molovo/revolver", lazy:true
#GENCOMPL_FPATH=$LOCAL_ZDOTDIR/completions
#zplug "RobSis/zsh-completion-generator"

zplug "zsh-users/zsh-completions"
zplug "akatrevorjay/nix-zsh-completions"

zplug "hlissner/zsh-autopair"
zplug "zsh-users/zsh-syntax-highlighting", nice:15

