#!/bin/zsh

zplugins.load "zsh-users/zsh-history-substring-search"
zplugins.load "akatrevorjay/fasd"

zplugins.load "willghatch/zsh-hooks"
zplugins.load "mafredri/zsh-async"

#zplugins.load "akatrevorjay/composure"
zplugins.load "psprint/zsnapshot"
zplugins.load "mollifier/zload"
zplugins.load "akatrevorjay/speedread"

## ~~~~~~~~~~~
## completions
## ~~~~~~~~~~~
GENCOMPL_FPATH=$LOCAL_ZDOTDIR/completions
zplugins.load "RobSis/zsh-completion-generator"

zplugins.load "zsh-users/zsh-completions"

#zplugins.load 'thewtex/tmux-mem-cpu-load' --post-update 'make'
#zplugins.load "uvaes/fzf-marks"
zplugins.load-all-in plugins-extra
zplugins.load-all-in plugins-trevorj

## ~~~~~~~~
## compinit
## ~~~~~~~~
zplugins.load-all-in zplugins-compinit

## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## plugins that must load past compinit
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# zplugins.load "hlissner/zsh-autopair"
zplugins.load "akatrevorjay/zsh-autopair"
# zplugins.load "zsh-users/zsh-syntax-highlighting" --defer 2
zplugins.load "zdharma/fast-syntax-highlighting"

zplugins.load "b4b4r07/zsh-vimode-visual"

