#!/bin/zsh
set -eo pipefail
#set -xv

db="$HOME/.mail"
qry="path:gmail/**"
last_sync_rev_file="$db/.last_sync_rev"
pre_vars_file="$db/.notmuch_new_pre_vars"

function death() {
  echo "=> death: $1" >&2
  exit 1
}

echo "=> full sync on $db"
if [ -e $last_sync_rev_file ]; then
  last_rev=$(cat $last_sync_rev_file)
else
  last_rev=0
fi
pre_rev=$(notmuch_get_revision $db)

# sync tags local-to-remote
#    --more-verbose \
full_qry="$qry AND lastmod:${last_rev}"
if [[ $last_rev -ne $pre_rev ]]; then
    full_qry+="..${pre_rev}"

    keywsync -m $db -q "$full_qry" -t -f -v \
        || death "local-to-remote did not complete."
fi

pre_mtime=$( date +%s )

declare -p last_rev pre_rev pre_mtime > "$pre_vars_file"

