#!/bin/zsh
setopt LOCAL_OPTIONS EXTENDED_GLOB NULLGLOB
local function_glob='^([_.]*|prompt_*_setup|README*|*.plugin.zsh)(-.N:t)'
local funcs=(${^argv}/${~function_glob})
[[ $#funcs -gt 0 ]] || continue
autoload -Uz ${(@)funcs}
