#!/bin/zsh

load-env-file() {
    local file=${1:-".env"}

    local contents=$(sed -e '/^\s*#/d' $file)
    contents=(${(f)contents})

    local i
    for i in $contents; do
        k=${i%%=*}; v=${i#*=}
        export $i
    done
}

load-env-file "$@"
