#!/bin/zsh

function max() {
	local sorted=(${(n)argv})
	[[ $#sorted -eq 0 ]] \
		|| echo ${sorted[-1]}
}

function min() {
	local sorted=(${(n)argv})
	[[ $#sorted -eq 0 ]] \
		|| echo ${sorted[1]}
}

"$0" "$@"
