#!/bin/zsh
#
# Output a cursor randomly on term. Stupid, lol.
#

if [[ -z $reset_color ]]; then
    autoload -Uz colors
    colors
fi

local ncols=$(tput cols)
local nlines=$(tput lines)

local col=$(( $RANDOM % $ncols ))
local line=$(( $RANDOM % $nlines ))

tput sc
tput cup $line $col
tput rev
echo -e "${reset_color}${bold_color}${fg[white]}${reset_color}"
tput sgr0
tput rc

