#!/bin/zsh

usage() {
    echo "Usage: $0 [FILES+]" >&2
}

[ $# -gt 0 ] || set -- --help
zparseopts -D -- h=help -help=help

if [ -n "$help" ]; then
    usage
    return
fi

# Source N files if accessible
local file
for file in "$@"; do
    [[ ! -r "$file" ]] || source "$file"
done

