#!/bin/zsh

[ $# -gt 0 ] || set -- $ZSH_THEME $USER default

local names=("$@")
[[ -z $SSH_CONNECTION ]] || names+=(${^names}-ssh $names ssh)
[[ -z $TMUX ]] || names=(${^names}-tmux $names tmux)

for fn in ${^ZDOTDIRS}/themes/${^names}{,.zsh,.sh}(-.N); do
    source $fn
    return
done

return 1
