#!/bin/zsh

[ $# -gt 0 ] || set -- $ZSH_THEME $USER default

local name
for name in "$@"; do
    for fn in ${^ZDOTDIRS}/themes/$name{,.zsh,.sh}(-.N); do
        source $fn
        return 0
    done
done
return 1

