#!/bin/zsh

[ $# -gt 0 ] || set -- $ZSH_THEME $USER default

local name
for name in "$@"; do
    names=()
    [[ -z $SSH_CONNECTION ]] || names+=($name-remote)
    names+=($name)

    for fn in ${^ZDOTDIRS}/themes/${^names}{,.zsh,.sh}(-.N); do
        source $fn
        return 0
    done
done
return 1

