#!/bin/zsh

# oh-my-shit
#zgen oh-my-zsh
#zgen prezto

# oh-my-shit plugins (try to avoid)
#zgen oh-my-zsh plugins/git
#zgen oh-my-zsh plugins/sudo
#zgen oh-my-zsh plugins/command-not-found

# theme
#zgen oh-my-zsh themes/arrow

plugins=(
	akatrevorjay/composure
	psprint/zsnapshot
	mollifier/zload
	kennethreitz/autoenv

	#akatrevorjay/macosx-shell-scripts
	#psprint/zsh-cmd-architect
	#psprint/zsh-editing-workbench
	#psprint/zsh-navigation-tools

	${(@)plugins}

	zsh-users/zsh-completions
	zsh-users/zsh-history-substring-search
	zsh-users/zsh-syntax-highlighting
)
