#!/bin/zsh

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Def
setopt extendedglob kshglob
setopt nullglob
setopt interactivecomments

umask 022

# Why in the world is this enabled by default on Linux? zgen?
zmodload -i zsh/stat
disable stat

# zgen
ZGEN_RESET_ON_CHANGE=(
	#{$LOCAL_ZDOTDIR,$ZDOTDIR}/zsh{env,rc,plugins}(.)
	{$LOCAL_ZDOTDIR,$ZDOTDIR}/zsh{env,rc,plugins}
)
source "$HOME/.zgen/zgen.zsh"

# plugin conf
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root line)

# if the init scipt doesn't exist
if ! zgen saved; then
	echo "Creating a zgen save"

	# TODO check plugins difference on hook and auto-load

	# bulk load
	plugins=(
		$LOCAL_ZDOTDIR/plugins/*(/)
		$ZDOTDIR/plugins/*(/)
	)
	source-with-force {$LOCAL_ZDOTDIR,$ZDOTDIR}/zshplugins
	echo ${(F)plugins[@]} | zgen loadall

	# save all to init script
	zgen save
fi

# Set up the prompt
#autoload -Uz promptinit
#promptinit
#prompt walters
source "$ZDOTDIR/themes/airline2.zsh"

# local
# TODO Move to $XDG local path
source-with-force "$LOCAL_ZDOTDIR/zshrc"

# This is annoying to have earlier.
#setopt warncreateglobal
