#!/bin/zsh
# order of preference: aria2c, axel, wget, curl. This order is derrived from speed based on personal tests.
if (( ${+commands[aria2c]} )); then
    alias get='aria2c --max-connection-per-server=5 --continue'
elif (( ${+commands[axel]} )); then
    alias get='axel --num-connections=5 --alternate'
elif (( ${+commands[wget]} )); then
    alias get='wget --continue --progress=bar --timestamping'
elif (( ${+commands[curl]} )); then
    alias get='curl --continue-at - --location --progress-bar --remote-name --remote-time'
else
	echo "Cannot find a single downloaded" >&2
	return 127
fi
